# Form implementation generated from reading ui file 'C:\Users\admin\Desktop\PYTHON_2022\python_study_different\GUI_different\Udemy\Qt_UI\DB_connect.ui'
#
# Created by: PyQt6 UI code generator 6.2.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.
import mysql.connector as mc
from PyQt6 import QtCore, QtGui, QtWidgets



class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(600, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pb_create = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pb_create.setFont(font)
        self.pb_create.setObjectName("pb_create")

        self.pb_create.clicked.connect(self.create_db)

        self.horizontalLayout_2.addWidget(self.pb_create)
        self.pb_connectdb = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pb_connectdb.setFont(font)
        self.pb_connectdb.setObjectName("pb_connectdb")

        self.pb_connectdb.clicked.connect(self.connect_db)

        self.horizontalLayout_2.addWidget(self.pb_connectdb)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.result = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.result.setFont(font)
        self.result.setText("")
        self.result.setObjectName("result")
        self.verticalLayout.addWidget(self.result)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def create_db(self):
        try:
            mydb = mc.connect(

                host = '192.168.2.165',
                user = 'admin',
                password = '0gfyfctyr0MYSQL'

            )
            print('connection established')
            cursor = mydb.cursor()
            dbname = self.lineEdit.text()
            print(dbname)
            cursor.execute(f'CREATE DATABASE IF NOT EXISTS {dbname}')
            self.result.setText(f'Database {dbname} created')

        except mc.Error as e:
            self.result.setText('Database creation failed')

    def connect_db(self):
        try:
            mydb = mc.connect(

                host = '192.168.2.165',
                user = 'admin',
                password = '0gfyfctyr0MYSQL',
                database = self.lineEdit.text()
            )

            self.result.setText('Connection sucsesful')

        except:
            self.result.setText('Connection Error')

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "DataBase Name:"))
        self.pb_create.setText(_translate("Form", "Create DB"))
        self.pb_connectdb.setText(_translate("Form", "DB connection"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
