# Form implementation generated from reading ui file 'C:\Users\admin\Desktop\PYTHON_2022\python_study_different\GUI_different\Udemy\Qt_UI\calendar_ex.ui'
#
# Created by: PyQt6 UI code generator 6.2.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(600, 600)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.calendarWidget = QtWidgets.QCalendarWidget(Form)
        self.calendarWidget.setStyleSheet("QCalendarWidget QToolButton {\n"
"\n"
"height:40px;\n"
"width:150px;\n"
"color:white;\n"
"font-size:20px;\n"
"icon-size:56px, 56px;\n"
"background-color:black;\n"
"\n"
"}\n"
"\n"
"QCalendarWidget QWidget {\n"
"\n"
"alternate-background-color:rgb(128,128,128)\n"
"\n"
"}\n"
"\n"
"QCalendarWidget QAbstractItemView:enabled {\n"
"\n"
"font-size:18px;\n"
"color:rgb(180,180,180);\n"
"background-color:black;\n"
"selection-background-color:rgb(64,64,64);\n"
"selection-color:rgb(0,255,0);\n"
"\n"
"}\n"
"")
        self.calendarWidget.setObjectName("calendarWidget")
        self.horizontalLayout.addWidget(self.calendarWidget)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.spinBox = QtWidgets.QSpinBox(Form)
        self.spinBox.setObjectName("spinBox")
        self.horizontalLayout_2.addWidget(self.spinBox)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.pushButton = QtWidgets.QPushButton(Form)

        self.pushButton.clicked.connect(self.calculate)

        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.reservation = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.reservation.setFont(font)
        self.reservation.setText("")
        self.reservation.setObjectName("reservation")
        self.verticalLayout.addWidget(self.reservation)
        self.result = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.result.setFont(font)
        self.result.setText("")
        self.result.setObjectName("result")
        self.verticalLayout.addWidget(self.result)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)


    def calculate(self):
        roomrent = 40
        dateSelected = self.calendarWidget.selectedDate()
        dateinstring = str(dateSelected.toPyDate())
        numDays = self.spinBox.value()

        self.reservation.setText(f'Date of Reservation {dateinstring}, number of days {numDays}')
        total = roomrent * numDays

        self.result.setText(f'Room rent for single day {roomrent}, Total Amount {total}')

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Date of Reservation"))
        self.label_2.setText(_translate("Form", "Number of Days"))
        self.pushButton.setText(_translate("Form", "Calculate"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
