# Form implementation generated from reading ui file 'C:\Users\admin\Desktop\PYTHON_2022\python_study_different\GUI_different\Udemy\Qt_UI\check_box_demo.ui'
#
# Created by: PyQt6 UI code generator 6.2.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(700, 500)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.cb_pizza = QtWidgets.QCheckBox(Dialog)

        self.cb_pizza.stateChanged.connect(self.chck_selected)

        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.cb_pizza.setFont(font)
        self.cb_pizza.setObjectName("cb_pizza")
        self.verticalLayout.addWidget(self.cb_pizza)
        self.cb_salad = QtWidgets.QCheckBox(Dialog)

        self.cb_salad.stateChanged.connect(self.chck_selected)

        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.cb_salad.setFont(font)
        self.cb_salad.setObjectName("cb_salad")
        self.verticalLayout.addWidget(self.cb_salad)
        self.cb_sausage = QtWidgets.QCheckBox(Dialog)

        self.cb_sausage.stateChanged.connect(self.chck_selected)

        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.cb_sausage.setFont(font)
        self.cb_sausage.setObjectName("cb_sausage")
        self.verticalLayout.addWidget(self.cb_sausage)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.label_3 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("QLabel\n"
"{\n"
"color:red\n"
"}")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def chck_selected(self):
        price = 10

        if self.cb_salad.isChecked():
            price+=4
        if self.cb_pizza.isChecked():
            price+=3
        if self.cb_sausage.isChecked():
            price+=5
        self.label_3.setText(f'Total price: {price}')

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Regular Tuna Price: 10"))
        self.label_2.setText(_translate("Dialog", "Select More:"))
        self.cb_pizza.setText(_translate("Dialog", "Pizza: 3"))
        self.cb_salad.setText(_translate("Dialog", "Salad: 4"))
        self.cb_sausage.setText(_translate("Dialog", "Sausage: 5"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
