# Form implementation generated from reading ui file 'C:\Users\admin\Desktop\PYTHON_2022\python_study_different\GUI_different\Udemy\Qt_UI\message.ui'
#
# Created by: PyQt6 UI code generator 6.2.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QDialog, QMessageBox


class Ui_Dialog(QDialog):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 107)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Dialog)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.about = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.about.setFont(font)
        self.about.setObjectName("about")
        self.horizontalLayout.addWidget(self.about)

        self.about.clicked.connect(self.about_m)

        self.info = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.info.setFont(font)
        self.info.setObjectName("info")

        self.info.clicked.connect(self.info_m)

        self.horizontalLayout.addWidget(self.info)
        self.warning = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.warning.setFont(font)
        self.warning.setObjectName("warning")

        self.warning.clicked.connect(self.warning_m)

        self.horizontalLayout.addWidget(self.warning)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.about.setText(_translate("Dialog", "About"))
        self.info.setText(_translate("Dialog", "Info"))
        self.warning.setText(_translate("Dialog", "Warning"))

    def warning_m(self):
        QMessageBox.warning(self, 'Warning', 'This is warning message')

    def info_m(self):
        QMessageBox.information(self, 'Info', 'This is info message')

    def about_m(self):
        QMessageBox.about(self, 'About', 'This is description message')

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
