# Form implementation generated from reading ui file 'C:\Users\admin\Desktop\PYTHON_2022\python_study_different\GUI_different\Udemy\Qt_UI\spin_box_pen+sugar.ui'
#
# Created by: PyQt6 UI code generator 6.2.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(600, 200)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.pen_price = QtWidgets.QLineEdit(Form)
        self.pen_price.setObjectName("pen_price")
        self.horizontalLayout.addWidget(self.pen_price)
        self.sb = QtWidgets.QSpinBox(Form)
        self.sb.setObjectName("sb")
        self.horizontalLayout.addWidget(self.sb)
        self.total_pen_price = QtWidgets.QLineEdit(Form)
        self.total_pen_price.setObjectName("total_pen_price")
        self.horizontalLayout.addWidget(self.total_pen_price)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.sugar_price = QtWidgets.QLineEdit(Form)
        self.sugar_price.setObjectName("sugar_price")
        self.horizontalLayout_2.addWidget(self.sugar_price)
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(Form)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.horizontalLayout_2.addWidget(self.doubleSpinBox)
        self.total_suga_price = QtWidgets.QLineEdit(Form)
        self.total_suga_price.setObjectName("total_suga_price")
        self.horizontalLayout_2.addWidget(self.total_suga_price)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.total = QtWidgets.QLabel(Form)

        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.total.setFont(font)
        self.total.setText("")
        self.total.setObjectName("total")
        self.verticalLayout.addWidget(self.total)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

        # self.sb.valueChanged.connect(self.first_res)
        # self.doubleSpinBox.valueChanged.connect(self.second_res)

        self.sb.editingFinished.connect(self.first_res)
        self.doubleSpinBox.editingFinished.connect(self.second_res)

    def first_res(self):
        penPrice = float(self.pen_price.text())
        totalpp = self.sb.value()*penPrice
        self.total_pen_price.setText(str(totalpp))

    def second_res(self):
        sugarPrice = float(self.sugar_price.text())
        totalsp = self.doubleSpinBox.value()*sugarPrice
        self.total_suga_price.setText(str(totalsp))

        totalpp = float(self.total_pen_price.text())
        totalamount = totalpp + totalsp

        self.total.setText(f'TotalPrice: {totalamount}')

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Pen Price"))
        self.label_2.setText(_translate("Form", "Sugar Price"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
