# Form implementation generated from reading ui file 'C:\Users\admin\Desktop\PYTHON_2022\python_study_different\GUI_different\Udemy\Qt_UI\LWappCRUD.ui'
#
# Created by: PyQt6 UI code generator 6.2.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QDialog, QInputDialog, QLineEdit, QMessageBox


class Ui_Dialog(QDialog):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(700, 700)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Dialog)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.listWidget = QtWidgets.QListWidget(Dialog)
        self.listWidget.setObjectName("listWidget")
        self.horizontalLayout.addWidget(self.listWidget)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.pb_add = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pb_add.setFont(font)
        self.pb_add.setObjectName("pb_add")

        self.pb_add.clicked.connect(self.add_item)

        self.verticalLayout.addWidget(self.pb_add)
        self.pb_edit = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pb_edit.setFont(font)
        self.pb_edit.setObjectName("pb_edit")

        self.pb_edit.clicked.connect(self.edit_item)

        self.verticalLayout.addWidget(self.pb_edit)
        self.pb_remove = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pb_remove.setFont(font)
        self.pb_remove.setObjectName("pb_remove")
        self.verticalLayout.addWidget(self.pb_remove)

        self.pb_remove.clicked.connect(self.remove_item)

        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.pb_sort = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pb_sort.setFont(font)
        self.pb_sort.setObjectName("pb_sort")

        self.pb_sort.clicked.connect(self.sort_item)

        self.verticalLayout.addWidget(self.pb_sort)
        self.horizontalLayout.addLayout(self.verticalLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def add_item(self):
        row = self.listWidget.currentRow()
        title = 'Add Item'
        data, ok = QInputDialog.getText(self, title, title)

        if ok and data is not None:
            self.listWidget.insertItem(row, data)

    def edit_item(self):
        row = self.listWidget.currentRow()
        item = self.listWidget.item(row)

        if item is not None:
            title = 'Edit Item'
            data, ok = QInputDialog.getText(self, title, title, QLineEdit.EchoMode.Normal, item.text())
            if ok and data is not None:
                item.setText(data)


    def remove_item(self):
        row = self.listWidget.currentRow()
        item = self.listWidget.item(row)

        if item is None:
            return
        reply = QMessageBox.question(self, 'Remove Item', 'Do you want to remove Item?', QMessageBox.StandardButton.Yes|QMessageBox.StandardButton.No)

        if reply == QMessageBox.StandardButton.Yes:
            self.listWidget.takeItem(row)


    def sort_item(self):
        self.listWidget.sortItems()

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pb_add.setText(_translate("Dialog", "Add"))
        self.pb_edit.setText(_translate("Dialog", "Edit"))
        self.pb_remove.setText(_translate("Dialog", "Remove"))
        self.pb_sort.setText(_translate("Dialog", "Sort"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
