# Form implementation generated from reading ui file 'addmember.ui'
#
# Created by: PyQt6 UI code generator 6.2.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import mysql.connector as mc
from dbconnect import connect_to_db
from string_split import string_split


class Member_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(450, 450)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lineEdit_membername = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_membername.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit_membername.setFont(font)
        self.lineEdit_membername.setObjectName("lineEdit_membername")
        self.verticalLayout.addWidget(self.lineEdit_membername)
        self.lineEdit_membermobile = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_membermobile.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit_membermobile.setFont(font)
        self.lineEdit_membermobile.setObjectName("lineEdit_membermobile")
        self.verticalLayout.addWidget(self.lineEdit_membermobile)
        self.lineEdit_memberemail = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_memberemail.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit_memberemail.setFont(font)
        self.lineEdit_memberemail.setObjectName("lineEdit_memberemail")
        self.verticalLayout.addWidget(self.lineEdit_memberemail)
        self.pushButton_save = QtWidgets.QPushButton(Dialog)

        self.pushButton_save.clicked.connect(self.insert_member)

        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_save.setFont(font)
        self.pushButton_save.setStyleSheet("QPushButton {\n"
"\n"
"background-color: grey;\n"
"color: white;\n"
"\n"
"}")
        self.pushButton_save.setObjectName("pushButton_save")
        self.verticalLayout.addWidget(self.pushButton_save)
        self.label_result = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_result.setFont(font)
        self.label_result.setText("")
        self.label_result.setObjectName("label_result")
        self.verticalLayout.addWidget(self.label_result)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def insert_member(self):

        mydb, connection = connect_to_db()

        if connection == True:

            print('Connection is Established')

            name = self.lineEdit_membername.text()
            mobile = self.lineEdit_membermobile.text()
            email = self.lineEdit_memberemail.text()

            if name == '' or mobile == '' or email == '':
                self.label_result.setText('Please add all fields')
                self.label_result.setStyleSheet('color:red')

            else:
                try:
                    mycursor = mydb.cursor()
                    query = f'insert into tbl_addmember (name, mobile, email)  VALUE (%s, %s, %s)'
                    value = (name, mobile, email)
                    mycursor.execute(query, value)
                    mydb.commit()
                    self.label_result.setText('Information added successfully')
                    self.label_result.setStyleSheet('color:green')
                    self.lineEdit_membername.setText('')
                    self.lineEdit_membermobile.setText('')
                    self.lineEdit_memberemail.setText('')
                except Exception as e:
                    e = string_split(str(e))
                    self.label_result.setText('Can\'t add information to DB' + '\n' + e)
                    self.label_result.setStyleSheet('color:red')

        else:
            self.label_result.setText('Not connected to DB' + '\n' + string_split(str(connection)))
            self.label_result.setStyleSheet('color:red')

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Insert Member"))
        self.lineEdit_membername.setPlaceholderText(_translate("Dialog", "Please Enter Member Name"))
        self.lineEdit_membermobile.setPlaceholderText(_translate("Dialog", "Please Enter Member Mobile"))
        self.lineEdit_memberemail.setPlaceholderText(_translate("Dialog", "Please Enter Member Email"))
        self.pushButton_save.setText(_translate("Dialog", "Insert Member"))

