# Form implementation generated from reading ui file 'C:\Users\admin\Desktop\PYTHON_2022\python_study_different\DS_exam\interface\interface.ui'
#
# Created by: PyQt6 UI code generator 6.2.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(700, 475)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        Form.setFont(font)
        Form.setStyleSheet("QWidget{\n"
"\n"
"font: 75 14pt \"MS Shell Dlg 2\";\n"
"\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_question = QtWidgets.QLabel(Form)
        self.label_question.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_question.setFont(font)
        self.label_question.setText("")
        self.label_question.setObjectName("label_question")
        self.verticalLayout.addWidget(self.label_question)
        self.pushButton_new_question = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.pushButton_new_question.setFont(font)
        self.pushButton_new_question.setObjectName("pushButton_new_question")
        self.verticalLayout.addWidget(self.pushButton_new_question)
        self.lineEdit_answer = QtWidgets.QLineEdit(Form)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.lineEdit_answer.setFont(font)
        self.lineEdit_answer.setStyleSheet("QLineEdit{\n"
"\n"
"    font: 75 14pt \"MS Shell Dlg 2\";\n"
"\n"
"}")
        self.lineEdit_answer.setText("")
        self.lineEdit_answer.setFrame(False)
        self.lineEdit_answer.setObjectName("lineEdit_answer")
        self.verticalLayout.addWidget(self.lineEdit_answer)
        self.pushButton_send = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.pushButton_send.setFont(font)
        self.pushButton_send.setCheckable(False)
        self.pushButton_send.setObjectName("pushButton_send")
        self.verticalLayout.addWidget(self.pushButton_send)
        self.label_answer_result = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_answer_result.setFont(font)
        self.label_answer_result.setText("")
        self.label_answer_result.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_answer_result.setObjectName("label_answer_result")
        self.verticalLayout.addWidget(self.label_answer_result)
        self.label = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label.setFont(font)
        self.label.setStyleSheet("QLabel{\n"
"\n"
"color: red\n"
"\n"
"}")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_right_answer = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_right_answer.setFont(font)
        self.label_right_answer.setText("")
        self.label_right_answer.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_right_answer.setObjectName("label_right_answer")
        self.verticalLayout.addWidget(self.label_right_answer)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton_new_question.setText(_translate("Form", "New Question"))
        self.lineEdit_answer.setPlaceholderText(_translate("Form", "Type your answer here"))
        self.pushButton_send.setText(_translate("Form", "Send Answer"))
        self.label.setText(_translate("Form", "ПРАВИЛЬНЫЙ ОТВЕТ"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
